"""
Postmortem Agent - Generate comprehensive postmortem document
"""
import logging
from datetime import datetime
from typing import Optional
from jinja2 import Template

from app.models.state import (
    IncidentState, TriageResult, ForensicsResult,
    RootCauseAnalysis, FixProposal
)

logger = logging.getLogger(__name__)


# Postmortem template
POSTMORTEM_TEMPLATE = """# Incident Postmortem: {{ incident_id }}

**Date:** {{ timestamp }}  
**Severity:** {{ severity }}  
**Status:** Resolved  
**Duration:** {{ duration }}

---

## Executive Summary

{{ executive_summary }}

---

## Timeline

{% for event in timeline %}
- **{{ event.time }}** - {{ event.description }}
{% endfor %}

---

## Root Cause Analysis

### Problem Statement
{{ problem_statement }}

### Root Cause
{{ root_cause }}

### Technical Details
{% for detail in technical_details %}
- {{ detail }}
{% endfor %}

### Affected Components
{% for component in affected_components %}
- **{{ component.name }}**: {{ component.description }}
{% endfor %}

---

## Resolution

### Fix Applied
{{ fix_description }}

### Files Modified
{% for file in files_modified %}
- `{{ file }}`
{% endfor %}

### Code Changes
```diff
{{ patch_preview }}
```

---

## Impact Assessment

- **Severity Level:** {{ severity }}
- **Service Affected:** {{ service }}
- **Error Type:** {{ error_type }}
- **User Impact:** {{ user_impact }}

---

## Action Items

### Immediate Actions (Completed)
{% for action in immediate_actions %}
- [x] {{ action }}
{% endfor %}

### Follow-up Actions
{% for action in followup_actions %}
- [ ] {{ action }}
{% endfor %}

---

## Lessons Learned

### What Went Well
{% for item in went_well %}
- {{ item }}
{% endfor %}

### What Could Be Improved
{% for item in improvements %}
- {{ item }}
{% endfor %}

### Prevention Measures
{% for measure in prevention_measures %}
- {{ measure }}
{% endfor %}

---

## Supporting Information

### Recent Changes
{% for commit in recent_commits %}
- `{{ commit.hash }}` by {{ commit.author }} ({{ commit.date }}): {{ commit.message }}
{% endfor %}

### Related Documentation
- Root Cause Analysis: See technical details above
- Fix PR: {{ pr_title }}
- Monitoring Dashboard: [Link to dashboard]

---

## Appendix

### Investigation Process
This incident was analyzed using Sherlock AI Incident Response Co-pilot, powered by IBM Bob.

**Analysis Pipeline:**
1. **Triage** - Classified incident severity and error type
2. **Forensics** - Gathered git history and code ownership data
3. **Root Cause Analysis** - Deep code analysis with full repository context (IBM Bob)
4. **Fix Generation** - Automated patch generation (IBM Bob)
5. **Postmortem** - Automated documentation generation

**Confidence Score:** {{ confidence }}

---

*Generated by Sherlock AI Incident Response Co-pilot*  
*Incident ID: {{ incident_id }}*  
*Generated at: {{ timestamp }}*
"""


class PostmortemAgent:
    """Agent untuk generate postmortem document"""
    
    def __init__(self):
        """Initialize Postmortem Agent"""
        self.template = Template(POSTMORTEM_TEMPLATE)
    
    def generate(
        self,
        incident_state: IncidentState,
        correlation_id: Optional[str] = None
    ) -> str:
        """
        Generate postmortem markdown dari incident state.
        
        Args:
            incident_state: Complete incident state dengan semua agent results
            correlation_id: Optional ID untuk tracking
            
        Returns:
            Postmortem markdown string
        """
        log_prefix = f"[{correlation_id}]" if correlation_id else ""
        logger.info(f"{log_prefix} Generating postmortem document")
        
        # Extract data dari state
        triage = incident_state.triage
        forensics = incident_state.forensics
        root_cause = incident_state.root_cause
        fix = incident_state.fix
        
        # Build context untuk template
        context = self._build_template_context(
            incident_state,
            triage,
            forensics,
            root_cause,
            fix
        )
        
        # Render template
        postmortem = self.template.render(**context)
        
        logger.info(f"{log_prefix} Postmortem generated ({len(postmortem)} chars)")
        return postmortem
    
    def _build_template_context(
        self,
        state: IncidentState,
        triage: Optional[TriageResult],
        forensics: Optional[ForensicsResult],
        root_cause: Optional[RootCauseAnalysis],
        fix: Optional[FixProposal]
    ) -> dict:
        """Build context dictionary untuk Jinja2 template"""
        
        # Calculate duration
        duration = "< 5 minutes (automated analysis)"
        if state.created_at and state.updated_at:
            delta = state.updated_at - state.created_at
            minutes = int(delta.total_seconds() / 60)
            duration = f"{minutes} minutes"
        
        # Executive summary
        executive_summary = self._generate_executive_summary(
            triage, root_cause, fix
        )
        
        # Timeline
        timeline = self._generate_timeline(state)
        
        # Technical details
        technical_details = []
        if root_cause:
            technical_details = root_cause.reasoning_chain
        
        # Affected components
        affected_components = []
        if root_cause and root_cause.suspect_files:
            for sf in root_cause.suspect_files:
                affected_components.append({
                    'name': sf.path,
                    'description': sf.reason
                })
        
        # Fix description
        fix_description = "Automated fix generated and ready for review."
        if fix:
            fix_description = f"{fix.pr_title}\n\n{fix.pr_body[:500]}..."
        
        # Patch preview (first 20 lines)
        patch_preview = ""
        if fix and fix.patch_unified_diff:
            lines = fix.patch_unified_diff.split('\n')[:20]
            patch_preview = '\n'.join(lines)
            if len(fix.patch_unified_diff.split('\n')) > 20:
                patch_preview += "\n... (truncated)"
        
        # Action items
        immediate_actions = [
            "Incident detected and triaged",
            "Root cause identified through code analysis",
            "Fix generated and validated",
            "Postmortem documentation created"
        ]
        
        followup_actions = [
            "Review and test the generated fix",
            "Deploy fix to production",
            "Monitor for recurrence",
            "Update runbooks and documentation",
            "Conduct team retrospective"
        ]
        
        # Lessons learned
        went_well = [
            "Automated incident detection and triage",
            "Fast root cause identification with AI-powered code analysis",
            "Automated fix generation reduced manual debugging time",
            "Comprehensive postmortem generated automatically"
        ]
        
        improvements = [
            "Add more comprehensive test coverage",
            "Improve monitoring and alerting",
            "Enhance code review process",
            "Consider architectural improvements to prevent similar issues"
        ]
        
        prevention_measures = []
        if triage:
            error_type = triage.error_type.value.replace('_', ' ')
            prevention_measures = [
                f"Add specific tests for {error_type} scenarios",
                "Implement additional validation and error handling",
                "Add monitoring alerts for early detection",
                "Update coding guidelines to prevent similar issues"
            ]
        
        # Recent commits
        recent_commits = []
        if forensics and forensics.recent_commits:
            for commit in forensics.recent_commits[:5]:
                recent_commits.append({
                    'hash': commit.hash,
                    'author': commit.author,
                    'date': commit.date.strftime('%Y-%m-%d %H:%M'),
                    'message': commit.message
                })
        
        # Build context
        context = {
            'incident_id': state.incident_id,
            'timestamp': datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC'),
            'severity': triage.severity.value.upper() if triage else "UNKNOWN",
            'duration': duration,
            'executive_summary': executive_summary,
            'timeline': timeline,
            'problem_statement': state.raw_input[:500] + "..." if len(state.raw_input) > 500 else state.raw_input,
            'root_cause': root_cause.root_cause if root_cause else "Analysis in progress",
            'technical_details': technical_details,
            'affected_components': affected_components,
            'fix_description': fix_description,
            'files_modified': fix.files_modified if fix else [],
            'patch_preview': patch_preview,
            'service': triage.service if triage else "unknown",
            'error_type': triage.error_type.value.replace('_', ' ').title() if triage else "Unknown",
            'user_impact': self._assess_user_impact(triage),
            'immediate_actions': immediate_actions,
            'followup_actions': followup_actions,
            'went_well': went_well,
            'improvements': improvements,
            'prevention_measures': prevention_measures,
            'recent_commits': recent_commits,
            'pr_title': fix.pr_title if fix else "Fix pending",
            'confidence': f"{root_cause.confidence:.0%}" if root_cause else "N/A"
        }
        
        return context
    
    def _generate_executive_summary(
        self,
        triage: Optional[TriageResult],
        root_cause: Optional[RootCauseAnalysis],
        fix: Optional[FixProposal]
    ) -> str:
        """Generate executive summary"""
        if not triage:
            return "Incident analysis in progress."
        
        summary = f"A {triage.severity.value} severity incident was detected in the {triage.service} service. "
        
        if root_cause:
            summary += f"Root cause identified: {root_cause.root_cause[:200]}... "
        
        if fix:
            summary += f"An automated fix has been generated affecting {len(fix.files_modified)} file(s). "
        
        summary += "This incident was analyzed and resolved using AI-powered incident response automation."
        
        return summary
    
    def _generate_timeline(self, state: IncidentState) -> list:
        """Generate timeline dari agent events"""
        timeline = []
        
        # Add creation event
        timeline.append({
            'time': state.created_at.strftime('%H:%M:%S'),
            'description': 'Incident reported and analysis started'
        })
        
        # Add agent events
        for event in state.agent_events:
            if event.status.value == 'completed':
                timeline.append({
                    'time': event.timestamp.strftime('%H:%M:%S'),
                    'description': f'{event.agent_name.title()} agent completed: {event.message}'
                })
        
        # Add completion event
        if state.updated_at:
            timeline.append({
                'time': state.updated_at.strftime('%H:%M:%S'),
                'description': 'Analysis completed and postmortem generated'
            })
        
        return timeline
    
    def _assess_user_impact(self, triage: Optional[TriageResult]) -> str:
        """Assess user impact berdasarkan severity"""
        if not triage:
            return "Impact assessment pending"
        
        impact_map = {
            'critical': 'High - Service unavailable or severely degraded for all users',
            'high': 'Medium-High - Significant functionality impaired for subset of users',
            'medium': 'Medium - Minor functionality issues affecting some users',
            'low': 'Low - Minimal impact, edge case or non-critical feature'
        }
        
        return impact_map.get(triage.severity.value, "Unknown impact")


# Global instance
postmortem_agent = PostmortemAgent()


def generate(
    incident_state: IncidentState,
    correlation_id: Optional[str] = None
) -> str:
    """
    Convenience function untuk postmortem generation.
    
    Usage:
        postmortem_md = generate(incident_state)
    """
    return postmortem_agent.generate(incident_state, correlation_id)
